# Generated by Django 5.0.6 on 2024-07-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_remove_orderitem_subtotal_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
    ]
